package com.sponia.opyfunctioindemo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sponia.opyfunctioindemo.dao.User;
import com.sponia.opyfunctioindemo.dao.Step;

import com.sponia.opyfunctioindemo.dao.UserDao;
import com.sponia.opyfunctioindemo.dao.StepDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig stepDaoConfig;

    private final UserDao userDao;
    private final StepDao stepDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        stepDaoConfig = daoConfigMap.get(StepDao.class).clone();
        stepDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        stepDao = new StepDao(stepDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Step.class, stepDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        stepDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public StepDao getStepDao() {
        return stepDao;
    }

}
