package com.sponia.opyfunctioindemo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STEP".
 */
public class Step {

    /** Not-null value. */
    private String id;
    private String userId;
    /** Not-null value. */
    private String date;
    private Float stepCount;
    private Float acceleration;
    private String status;

    public Step() {
    }

    public Step(String id) {
        this.id = id;
    }

    public Step(String id, String userId, String date, Float stepCount, Float acceleration, String status) {
        this.id = id;
        this.userId = userId;
        this.date = date;
        this.stepCount = stepCount;
        this.acceleration = acceleration;
        this.status = status;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Float getStepCount() {
        return stepCount;
    }

    public void setStepCount(Float stepCount) {
        this.stepCount = stepCount;
    }

    public Float getAcceleration() {
        return acceleration;
    }

    public void setAcceleration(Float acceleration) {
        this.acceleration = acceleration;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
