package com.sponia.opyfunctioindemo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    /** Not-null value. */
    private String id;
    private String name;
    /** Not-null value. */
    private String sex;
    private Integer weight;
    private Integer today_steps;

    public User() {
    }

    public User(String id) {
        this.id = id;
    }

    public User(String id, String name, String sex, Integer weight, Integer today_steps) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.weight = weight;
        this.today_steps = today_steps;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getSex() {
        return sex;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getToday_steps() {
        return today_steps;
    }

    public void setToday_steps(Integer today_steps) {
        this.today_steps = today_steps;
    }

}
